### ISSUE TITLE
Requesting example for a simple language

### ISSUE THREAD

**Issue by rishavs** [opsidian/parsley#15]
Hi

I am trying to use Parsley for a simple language parser but am getting stuck around defining the ast and error handling. It would be great to have a few more examples - particularly of a small programming language like Lua or [Lox](https://craftinginterpreters.com/appendix-i.html).

**Comment by bandesz** [comment]
Hi @rishavs, you can find some examples in https://github.com/conflowio/conflow/tree/main/pkg/parsers.

A complex expression parser supporting variables can be found here: https://github.com/conflowio/conflow/blob/main/pkg/parsers/expression.go

The Conflow language itself is define here: https://github.com/conflowio/conflow/blob/main/pkg/parsers/main.go.

**Comment by rishavs** [comment]
Thank you!
